export default [
  {
    order: 0,
    src: 'src="https://ticket-backend.s3.amazonaws.com/static/covers/2022/11/12/banner/wine4.jpg"',
    alt: 'Text',
    title: 'There is no one who loves pain itself',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 1,
    src: 'https://img.elo7.com.br/product/original/3249FFD/quadro-decorativo-natureza-paisagem-mar-sol-coqueiro-ponte-quadro-belezas-naturais.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 2,
    src: 'https://www.grupoescolar.com/wp-content/uploads/2021/03/paisagem-2C.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 3,
    src: 'https://i0.wp.com/omeudiadia.com.br/wp-content/uploads/2022/04/paisagem-natural.jpg?resize=800%2C534&ssl=1',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 4,
    src: 'https://www.ocasaldafoto.com/wp-content/uploads/2018/09/Foto-de-Paisagem-Lago-da-Pampulha-Belo-Horizonte-Charles-Torres.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 5,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU-qQTiRaP8QN13CGPfT9bcU-2ZBJ3yKi0mw&usqp=CAU',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
  {
    order: 6,
    src: 'http://1.bp.blogspot.com/-5XOjJvW09zQ/UjtEqc523_I/AAAAAAAAmTo/dOHXSTw3pF8/s1600/PAISAGEM.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
    link: '/',
  },
];
