export default [
  {
    order: 0,
    src: 'https://www.heteroclito.fr/modules/Jssor/img/home/02.jpg',
    alt: 'Text',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 1,
    src: 'https://wowslider.com/sliders/demo-44/data1/images/bridge.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 2,
    src: 'http://wowslider.com/sliders/demo-18/data1/images/hongkong1081704.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 3,
    src: 'https://jssors8.azureedge.net/demos/img/gallery/980x380/044.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 4,
    src: 'https://jssors8.azureedge.net/demos/img/gallery/980x380/043.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 5,
    src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS12HsR4208xr5QaId3nomjIOEI28wTIiWx8KiiKmfcP6eZtQ98SxdSBT5H0in1N5o1Yw&usqp=CAU',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
  {
    order: 6,
    src: 'https://jssors8.azureedge.net/demos/img/gallery/980x380/045.jpg',
    alt: 'Zelda',
    title: 'What is Lorem Ipsum',
    description: 'There is no one who loves pain itself',
  },
];
